[package]
name = "party-member-list"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core" }
chirp-client = { path = "../../../../../lib/chirp/client" }
prost = "0.10"
redis-util = { path = "../../../../../lib/redis-util" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
