[package]
name = "chat-message-create-with-topic"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core", features = [] }
chirp-client = { path = "../../../../../lib/chirp/client" }
prost = "0.10"

chat-thread-get-or-create-for-topic = { path = "../../../chat-thread/ops/get-or-create-for-topic" }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

faker-user = { path = "../../../faker/ops/user" }
