[package]
name = "chat-message-worker"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
chirp-client = { path = "../../../../lib/chirp/client" }
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
lazy_static = "1.4.0"
chrono = "0.4"
util-chat = { package = "rivet-util-chat", path = "../../chat/util" }

chat-thread-participant-list = { path = "../../chat-thread/ops/participant-list" }

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }

chat-message-list = { path = "../ops/list" }
chat-thread-get-or-create-for-topic = { path = "../../chat-thread/ops/get-or-create-for-topic" }
