[package]
name = "team-billing-collect"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
rivet-operation = { path = "../../../../../lib/operation/core" }
futures-util = "0.3"
indoc = "1.0"
prost = "0.10"
rivet-connection = { path = "../../../../../lib/connection" }
chrono = "0.4"
rivet-pools = { path = "../../../../../lib/pools" }
rivet-runtime = { path = "../../../../../lib/runtime" }
tokio = { version = "1.29", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }

game-get = { path = "../../../game/ops/get" }
team-billing-aggregate = { path = "../../ops/billing-aggregate" }

[dependencies.sqlx]
version = "0.6"
default-features = false
features = [
	"runtime-tokio-native-tls",
	"postgres",
	"uuid",
	"json",
	"tls",
	"macros",
]

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

faker-team = { path = "../../../faker/ops/team" }
faker-mm-lobby = { path = "../../../faker/ops/mm-lobby" }
game-get = { path = "../../../game/ops/get" }
