[package]
name = "chat-thread-recent-for-user"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-operation = { path = "../../../../../lib/operation/core" }
chirp-client = { path = "../../../../../lib/chirp/client" }
lazy_static = "1.4"
chrono = "0.4"
prost = "0.10"
util-chat = { package = "rivet-util-chat", path = "../../../chat/util" }

chat-thread-get = { path = "../get" }
chat-thread-list-for-participant = { path = "../list-for-participant" }

[dependencies.sqlx]
version = "0.7"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }

chat-thread-get-or-create-for-topic = { path = "../get-or-create-for-topic" }
chat-thread-get-for-topic = { path = "../get-for-topic" }
faker-user = { path = "../../../faker/ops/user" }
