[package]
name = "rivet-util-party"
version = "0.1.0"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
