[package]
name = "team-dev-halt-collect"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
rivet-operation = { path = "../../../../../lib/operation/core" }
futures-util = "0.3"
indoc = "1.0"
prost = "0.10"
rivet-metrics = { path = "../../../../../lib/metrics" }
rivet-connection = { path = "../../../../../lib/connection" }
chrono = "0.4"
rivet-pools = { path = "../../../../../lib/pools" }
rivet-runtime = { path = "../../../../../lib/runtime" }
tokio = { version = "1.29", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }

team-dev-halt = { path = "../../ops/halt" }

[dependencies.sqlx]
version = "0.7"
default-features = false
features = [
	"postgres",
	"uuid",
	"json",
	"macros",
]

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
