[service]
name = "api-auth"
[runtime]
kind = "rust"

# New
[[api.router.mounts]]
path = "/auth"
subdomain = "api"

# Legacy
[[api.router.mounts]]
path = "/v1"
subdomain = "auth.api"

[secrets]
"turnstile/rivet_gg/secret_key" = { optional = true }
