[service]
name = "api-admin"

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/admin"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "admin.api"

[secrets]
"rivet/api_admin/token" = {}
