[service]
name = "api-admin"

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/v1"
subdomain = "admin.api"

[[api.router.mounts]]
path = "/admin"
subdomain = "api"

[secrets]
"rivet/api_admin/token" = {}
