[package]
name = "rivet-util-mm"
version = "0.1.0"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
bit-vec = "0.6"
rivet-util = { path = "../../../../lib/util/core" }
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.24", features = ["derive"] }
uuid = { version = "1", features = ["v4", "serde"] }
