[service]
name = "api-matchmaker"

[runtime]
kind = "rust"

# New
[[api.router.mounts]]
path = "/matchmaker"
subdomain = "api"

# Legacy
[[api.router.mounts]]
path = "/v1"
subdomain = "matchmaker.api"
