[service]
name = "api-matchmaker"

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/matchmaker"
subdomain = "api"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "matchmaker.api"
