[service]
name = "api-matchmaker"

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/matchmaker"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "matchmaker.api"

[cockroachdb]
min-connections = 8

