[package]
name = "party-redis-populate"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
rivet-operation = { path = "../../../../../lib/operation/core" }
indoc = "1.0"
prost = "0.10"
rivet-connection = { path = "../../../../../lib/connection" }
rivet-pools = { path = "../../../../../lib/pools" }
tokio = { version = "1.21", features = ["full"] }
futures-util = "0.3"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
