[service]
name = "api-module"

[runtime]
kind = "rust"

[api]

[[api.router.mounts]]
path = "/module"
subdomain = "api"

[[api.router.mounts]]
deprecated = true
path = "/v1"
subdomain = "module.api"

