[package]
name = "playground"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
rivet-operation = { path = "../../../../../lib/operation/core" }
chrono = "0.4"
futures-util = "0.3"
indoc = "1.0"
lazy_static = "1.4"
nomad-client = "0.0.9"
nomad-util = { path = "../../../../../lib/nomad-util" }
prost = "0.10"
reqwest = { version = "0.11", features = ["json"] }
rivet-cache = { path = "../../../../../lib/cache/build" }
rivet-connection = { path = "../../../../../lib/connection" }
rivet-health-checks = { path = "../../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../../lib/metrics" }
rivet-pools = { path = "../../../../../lib/pools" }
s3-util = { path = "../../../../../lib/s3-util" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.29", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
util-mm = { package = "rivet-util-mm", path = "../../../mm/util" }
uuid = { version = "1", features = ["v4"] }

build-create = { path = "../../../build/ops/create" }
build-get = { path = "../../../build/ops/get" }
cloud-version-get = { path = "../../../cloud/ops/version-get" }
cloud-version-publish = { path = "../../../cloud/ops/version-publish" }
game-get = { path = "../../../game/ops/get" }
game-namespace-get = { path = "../../../game/ops/namespace-get" }
game-namespace-list = { path = "../../../game/ops/namespace-list" }
region-get = { path = "../../../region/ops/get" }
region-list = { path = "../../../region/ops/list" }
upload-complete = { path = "../../../upload/ops/complete" }

[dependencies.sqlx]
version = "0.6"
default-features = false
features = [
	"runtime-tokio-native-tls",
	"postgres",
	"uuid",
	"json",
	"tls",
]

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
