[package]
name = "mm-gc-full"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-client = { path = "../../../../../lib/chirp/client" }
chrono = "0.4"
indoc = "1.0"
prost = "0.10"
rivet-connection = { path = "../../../../../lib/connection" }
rivet-operation = { path = "../../../../../lib/operation/core" }
rivet-pools = { path = "../../../../../lib/pools" }
rivet-runtime = { path = "../../../../../lib/runtime" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "json", "ansi"] }
util-mm = { package = "rivet-util-mm", path = "../../util" }

[dependencies.sqlx]
version = "0.7"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../../lib/chirp/worker" }
