[service]
name = "api-route"
essential = true
priority = 70

[runtime]
kind = "rust"

[[api.router.mounts]]
path = "/v1"
subdomain = "route.api"

[secrets]
"rivet/api_route/token" = {}

[databases]
redis-job = {}
