[package]
name = "chat-thread-worker"
version = "0.0.1"
edition = "2018"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
chirp-client = { path = "../../../../lib/chirp/client" }
rivet-health-checks = { path = "../../../../lib/health-checks" }
rivet-metrics = { path = "../../../../lib/metrics" }
rivet-runtime = { path = "../../../../lib/runtime" }
lazy_static = "1.4.0"
chrono = "0.4"

[dependencies.sqlx]
version = "0.7"
default-features = false

[dev-dependencies]
chirp-worker = { path = "../../../../lib/chirp/worker" }
