[package]
name = "rivet-util-chat"
version = "0.1.0"
edition = "2021"
authors = ["Rivet Gaming, LLC <developer@rivet.gg>"]
license = "Apache-2.0"

[dependencies]
rivet-util = { path = "../../../../lib/util/core" }
uuid = "1.1"
