name: docker-publish

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Install Nix
      run: |
        curl -L https://nixos.org/nix/install | sh
        . /home/runner/.nix-profile/etc/profile.d/nix.sh

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build Docker image using Nix
      run: |
        cd infra/docker/traffic_server
        nix-build docker.nix
        docker load < result

    - name: Push Docker image
      run: |
        GHCR_TAG="ghcr.io/rivet-gg/apache-traffic-server:latest"
        docker tag apache-traffic-server:latest "$GHCR_TAG"
        docker "$GHCR_TAG"

