name: foo

on:
  workflow_dispatch:
    inputs:
      version:
        description: "What's your favorite color?"
        required: false

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Echo
      - run: echo "hello"
