name: rust

on: push

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    # Enable fail-fast behavior
    shell: bash -e {0}

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo deny (svc)
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --manifest-path svc/Cargo.toml
      - name: cargo deny (lib/bolt)
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          arguments: --manifest-path lib/bolt/Cargo.toml
