name: service-containers-publish

on:
  push:
    branches:
      - main

defaults:
  run:
    # Enable fail-fast behavior
    shell: bash -e {0}

env:
  store: /home/runner/nix

jobs:
  service-containers-publish:
    runs-on: [self-hosted, linux, x64]

    steps:
      # MARK: Git
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - uses: ./.github/actions/pre-init-distributed
        with:
          SCCACHE_AWS_SECRET_ACCESS_KEY: ${{ secrets.SCCACHE_AWS_SECRET_ACCESS_KEY }}
          SCCACHE_AWS_ACCESS_KEY_ID: ${{ secrets.SCCACHE_AWS_ACCESS_KEY_ID }}
          DOCKER_CI_ACCESS_TOKEN: ${{ secrets.DOCKER_CI_ACCESS_TOKEN }}

      - name: Bolt up and push containers
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Cannot use --pure `https://github.com/NixOS/nixpkgs/issues/66716`
        run: nix-shell --run "bolt up --skip-deploy"
