[package]
name = "rivet-util-db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rivet-util = { path = "../../../../lib/util/core" }
global-error = { path = "../../../../lib/global-error" }
uuid = { version = "1", features = ["v4"] }
aes-gcm = "0.10"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
bs58 = "0.5.0"
tracing = "0.1"

